project:
  type: website

website:
  title: "My titleless website"
  navbar:
    left:
      - text: "Home"
        file: index.qmd
      - text: "Portfolio"
        file: Portfolio.qmd
      - text: "CV"
        file: CV.qmd
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: flatly
    css: styles.css

editor: visual

